name: Scout-REViewer-service
dependencies:
- python=3.9.5
- pip
- pip:
    - aiofiles
    - aiohttp
    - elementpath
    - fastapi
    - pydantic
    - pylint
    - pytest
    - python-dotenv
    - requests
    - typing
    - uvicorn[standard]
