name: Scout-REViewer-service
channels:
    - bioconda
    - conda-forge
dependencies:
- python
- reviewer
- trgt
- pip
- pip:
    - aiofiles
    - aiohttp
    - elementpath
    - fastapi
    - pydantic
    - pylint
    - pytest
    - python-dotenv
    - requests
    - typing
    - uvicorn[standard]
