name: Scout-REViewer-service
dependencies:
- python=3.9.5
- pip
- pip:
    - fastapi
    - uvicorn[standard]
    - typing
    - pydantic
    - aiohttp
    - aiofiles
    - pytest
    - starlette
    - requests
    - httpx
    - pytest-asyncio
    - pylint
